apiVersion: 1

deleteDatasources:
{% for item in datasources %}
  - name: {{ item.name }}
    orgId: 1
{% endfor %}

datasources:
{% for item in datasources %}
  - name: {{ item.name }}
    type: prometheus
    orgId: 1
    url: http://{{ item.hostname }}:{{ item.port }}
    access: proxy
    isDefault: {{ item.default }}
    editable: {{ item.editable }}
{% endfor %}

