---
- hosts: prometheus_grafana
  become: yes
  gather_facts: yes
  roles:
    - /home/ubuntu/devops_stand/prometheus 

- hosts: prometheus_grafana
  become: yes
  gather_facts: yes
  roles:
    - /home/ubuntu/devops_stand/grafana

- hosts: node
  become: yes
  gather_facts: yes
  roles:
    - /home/ubuntu/devops_stand/node-exporter
